package sharederrors

const (
	ErrCodeInvalidRequest                = "INVALID_REQUEST"
	ErrCodeInvalidData                   = "INVALID_DATA"
	ErrCodeAccountNotFound               = "ACCOUNT_NOT_FOUND"
	ErrCodeInsufficientFunds             = "INSUFFICIENT_FUNDS"
	ErrCodeInvalidAmount                 = "INVALID_AMOUNT"
	ErrCodeForbidden                     = "FORBIDDEN"
	ErrCodeCustomerNotFound              = "CUSTOMER_NOT_FOUND"
	ErrCodeAccountInactive               = "ACCOUNT_INACTIVE"
	ErrCodeSameAccount                   = "SAME_ACCOUNT_TRANSFER"
	ErrCodeUserAlreadyExists             = "USER_ALREADY_EXISTS"
	ErrCodeInvalidCredentials            = "INVALID_CREDENTIALS"
	ErrCodeContactNotVerified            = "CONTACT_NOT_VERIFIED"
	ErrCodeAccountApprovalRequired       = "ACCOUNT_APPROVAL_REQUIRED"
	ErrCodeUnauthorized                  = "UNAUTHORIZED"
	ErrCodeInvalidToken                  = "INVALID_TOKEN"
	ErrCodeInternal                      = "INTERNAL_ERROR"
	ErrCodeInvalidUserState              = "INVALID_USER_STATE"
	ErrCodeUserNotFound                  = "USER_NOT_FOUND"
	ErrCodeUserAlreadyActive             = "USER_ALREADY_ACTIVE"
	ErrCodeTransactionNotFound           = "TRANSACTION_NOT_FOUND"
	ErrCodeTransactionPasswordAlreadySet = "TRANSACTION_PASSWORD_ALREADY_SET"
	ErrCodeTransactionPasswordNotSet     = "TRANSACTION_PASSWORD_NOT_SET"
	ErrCodeTransactionPasswordInvalid    = "TRANSACTION_PASSWORD_INVALID"
	ErrCodeTransactionPasswordLocked     = "TRANSACTION_PASSWORD_LOCKED"
	ErrCodeTransactionPasswordRequired   = "TRANSACTION_PASSWORD_REQUIRED"
	ErrCodeStepUpEndpointNotAllowed      = "STEP_UP_ENDPOINT_NOT_ALLOWED"
	ErrCodeStepUpTokenRequired           = "STEP_UP_TOKEN_REQUIRED"
	ErrCodeStepUpTokenInvalid            = "STEP_UP_TOKEN_INVALID"
	ErrCodeStepUpTokenExpired            = "STEP_UP_TOKEN_EXPIRED"
	ErrCodeStepUpTokenConsumed           = "STEP_UP_TOKEN_CONSUMED"
	ErrCodeStepUpEndpointMismatch        = "STEP_UP_ENDPOINT_MISMATCH"
	ErrCodeInvalidInstallationID         = "INVALID_INSTALLATION_ID"
	ErrCodeInstallationMismatch          = "INSTALLATION_MISMATCH"
	ErrCodeInstallationRevoked           = "INSTALLATION_REVOKED"
	ErrCodeInstallationLimitReached      = "INSTALLATION_LIMIT_REACHED"
)
