package infrastructure

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/seu-usuario/bank-api/internal/auth/domain"
	"github.com/seu-usuario/bank-api/internal/database"
)

type PostgresContactVerificationRepository struct {
	db *pgxpool.Pool
}

var _ domain.ContactVerificationRepository = (*PostgresContactVerificationRepository)(nil)

// NewPostgresContactVerificationRepository creates a PostgreSQL-backed
// implementation of ContactVerificationRepository.
func NewPostgresContactVerificationRepository(db *pgxpool.Pool) *PostgresContactVerificationRepository {
	return &PostgresContactVerificationRepository{db: db}
}

// executor returns the current transaction executor when available in context,
// otherwise it falls back to the shared pool.
func (r *PostgresContactVerificationRepository) executor(ctx context.Context) dbExecutor {
	if tx, ok := database.TxFromContext(ctx); ok {
		return tx
	}

	return r.db
}

// CreateContactVerification persists a contact verification attempt. The ID is
// generated by the database. A new request for the same channel and target
// replaces the previous attempt.
func (r *PostgresContactVerificationRepository) CreateContactVerification(
	ctx context.Context,
	verification *domain.ContactVerification,
) error {
	query := `
		INSERT INTO contact_verifications (
			channel,
			target,
			token,
			expires_at,
			created_at
		)
		VALUES ($1, $2, $3, $4, $5)
		ON CONFLICT (target, channel)
		DO UPDATE SET
			id = gen_random_uuid(),
			token = EXCLUDED.token,
			verification_token = NULL,
			verified_at = NULL,
			expires_at = EXCLUDED.expires_at,
			created_at = EXCLUDED.created_at
		RETURNING id
	`

	err := r.executor(ctx).QueryRow(
		ctx,
		query,
		string(verification.Channel),
		verification.Target,
		verification.Token,
		verification.ExpiresAt,
		verification.CreatedAt,
	).Scan(&verification.ID)
	if err != nil {
		var pgErr *pgconn.PgError
		if errors.As(err, &pgErr) && pgErr.Code == "23514" {
			return domain.ErrInvalidData
		}

		return fmt.Errorf("create contact verification: %w", err)
	}

	return nil
}

// FindContactVerificationByID retrieves a contact verification by its primary ID.
// It returns nil, nil when no record is found.
func (r *PostgresContactVerificationRepository) FindContactVerificationByID(
	ctx context.Context,
	id uuid.UUID,
) (*domain.ContactVerification, error) {
	query := `
		SELECT
			id,
			channel,
			target,
			token,
			verification_token,
			verified_at,
			expires_at,
			created_at
		FROM contact_verifications
		WHERE id = $1
	`

	verification, err := scanContactVerification(r.executor(ctx).QueryRow(ctx, query, id))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}

		return nil, fmt.Errorf("find contact verification by id: %w", err)
	}

	return verification, nil
}

// FindContactVerificationByVerificationToken retrieves a contact verification
// by its confirmation token. It returns nil, nil when no record is found.
func (r *PostgresContactVerificationRepository) FindContactVerificationByVerificationToken(
	ctx context.Context,
	verificationToken string,
) (*domain.ContactVerification, error) {
	query := `
		SELECT
			id,
			channel,
			target,
			token,
			verification_token,
			verified_at,
			expires_at,
			created_at
		FROM contact_verifications
		WHERE verification_token = $1
	`

	verification, err := scanContactVerification(r.executor(ctx).QueryRow(ctx, query, verificationToken))
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}

		return nil, fmt.Errorf("find contact verification by verification token: %w", err)
	}

	return verification, nil
}

// ConfirmContactVerification stores the verification token and mark timestamp
// for a previously created verification attempt.
func (r *PostgresContactVerificationRepository) ConfirmContactVerification(
	ctx context.Context,
	id uuid.UUID,
	verificationToken string,
	verifiedAt time.Time,
) error {
	query := `
		UPDATE contact_verifications
		SET verification_token = $1,
		    verified_at = $2
		WHERE id = $3
	`

	result, err := r.executor(ctx).Exec(ctx, query, verificationToken, verifiedAt, id)
	if err != nil {
		return fmt.Errorf("confirm contact verification: %w", err)
	}
	if result.RowsAffected() == 0 {
		return domain.ErrContactVerificationNotFound
	}

	return nil
}

// scanContactVerification maps a query row into a domain ContactVerification,
// including nullable verification token and verified timestamp fields.
func scanContactVerification(s scanner) (*domain.ContactVerification, error) {
	var verification domain.ContactVerification
	var channel string
	var verificationToken sql.NullString
	var verifiedAt sql.NullTime

	err := s.Scan(
		&verification.ID,
		&channel,
		&verification.Target,
		&verification.Token,
		&verificationToken,
		&verifiedAt,
		&verification.ExpiresAt,
		&verification.CreatedAt,
	)
	if err != nil {
		return nil, err
	}

	verification.Channel = domain.ContactVerificationChannel(channel)
	if verificationToken.Valid {
		verification.VerificationToken = &verificationToken.String
	}
	if verifiedAt.Valid {
		verification.VerifiedAt = &verifiedAt.Time
	}

	return &verification, nil
}
