package infrastructure

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/seu-usuario/bank-api/internal/auth/domain"
	"github.com/seu-usuario/bank-api/internal/database"
	installationdomain "github.com/seu-usuario/bank-api/internal/installation/domain"
)

type PostgresSessionRepository struct {
	db *pgxpool.Pool
}

// Ensure PostgresSessionRepository implements the SessionRepository interface at
// compile time.
var _ domain.SessionRepository = (*PostgresSessionRepository)(nil)
var _ installationdomain.InstallationSessionInvalidator = (*PostgresSessionRepository)(nil)

// NewPostgresSessionRepository creates a new instance of PostgresSessionRepository
// with the provided pgxpool.Pool. This repository will be used to manage user
// sessions in a PostgreSQL database. It provides methods for creating sessions, finding sessions by token hash,
// and revoking sessions. The repository uses the pgx library to interact with
// the database and supports transactions through the context.
func NewPostgresSessionRepository(db *pgxpool.Pool) *PostgresSessionRepository {
	return &PostgresSessionRepository{db: db}
}

// executor returns the appropriate database executor based on the context. If a
// transaction is present in the context, it returns the transaction; otherwise,
// it returns the main database connection pool. This allows the repository methods
// to work seamlessly with both transactional and non-transactional contexts.
func (r *PostgresSessionRepository) executor(ctx context.Context) dbExecutor {
	if tx, ok := database.TxFromContext(ctx); ok {
		return tx
	}

	return r.db
}

// Create inserts a new session record into the user_sessions table with the provided
// user ID, token hash, and expiration time. The session ID is generated by the
// database. If the operation is successful, it returns nil; otherwise, it returns
// an error.
func (r *PostgresSessionRepository) Create(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) error {
	return r.CreateWithInstallation(ctx, domain.CreateSessionInput{
		UserID:    userID,
		TokenHash: tokenHash,
		ExpiresAt: expiresAt,
	})
}

func (r *PostgresSessionRepository) CreateWithInstallation(
	ctx context.Context,
	input domain.CreateSessionInput,
) error {
	query := `
		INSERT INTO user_sessions (
			user_id,
			token_hash,
			expires_at,
			installation_id
		)
		VALUES ($1, $2, $3, $4)
	`

	_, err := r.executor(ctx).Exec(ctx, query, input.UserID, input.TokenHash, input.ExpiresAt, input.InstallationID)
	return err
}

// FindByTokenHash retrieves a session from the user_sessions table based on the
// provided token hash. It returns the user ID, expiration time, a boolean indicating
// whether the session has been revoked, and an error if the operation fails.
// If no session is found with the given token hash, it returns a zero UUID,
// zero time, false for revoked, and nil for error.
func (r *PostgresSessionRepository) FindByTokenHash(ctx context.Context, tokenHash string) (uuid.UUID, time.Time, bool, error) {
	record, err := r.FindByTokenHashWithInstallation(ctx, tokenHash)
	if err != nil {
		return uuid.Nil, time.Time{}, false, err
	}
	if record == nil {
		return uuid.Nil, time.Time{}, false, nil
	}

	return record.UserID, record.ExpiresAt, record.Revoked, nil
}

func (r *PostgresSessionRepository) FindByTokenHashWithInstallation(
	ctx context.Context,
	tokenHash string,
) (*domain.SessionRecord, error) {
	query := `
		SELECT user_id, token_hash, expires_at, revoked_at, installation_id
		FROM user_sessions
		WHERE token_hash = $1
	`

	var userID uuid.UUID
	var storedTokenHash string
	var expiresAt time.Time
	var revokedAt *time.Time
	var installationID *uuid.UUID

	err := r.executor(ctx).QueryRow(ctx, query, tokenHash).Scan(
		&userID,
		&storedTokenHash,
		&expiresAt,
		&revokedAt,
		&installationID,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	return &domain.SessionRecord{
		UserID:         userID,
		TokenHash:      storedTokenHash,
		ExpiresAt:      expiresAt,
		Revoked:        revokedAt != nil,
		InstallationID: installationID,
	}, nil
}

// Revoke sets the revoked_at timestamp for a session in the user_sessions table
// based on the provided token hash. If the session is successfully revoked, it
// returns nil; if no session is found with the given token hash, it returns
// domain.ErrSessionNotFound; otherwise, it returns an error.
func (r *PostgresSessionRepository) Revoke(ctx context.Context, tokenHash string) error {
	query := `
		UPDATE user_sessions
		SET revoked_at = NOW()
		WHERE token_hash = $1
	`

	result, err := r.executor(ctx).Exec(ctx, query, tokenHash)
	if err != nil {
		return err
	}
	if result.RowsAffected() == 0 {
		return domain.ErrSessionNotFound
	}
	return nil
}

func (r *PostgresSessionRepository) RevokeByUserIDAndInstallationID(
	ctx context.Context,
	userID uuid.UUID,
	installationID uuid.UUID,
	revokedAt time.Time,
) error {
	query := `
		UPDATE user_sessions
		SET revoked_at = $3
		WHERE user_id = $1
			AND installation_id = $2
			AND revoked_at IS NULL
	`

	_, err := r.executor(ctx).Exec(ctx, query, userID, installationID, revokedAt.UTC())
	return err
}

func (r *PostgresSessionRepository) InvalidateByInstallationID(
	ctx context.Context,
	userID uuid.UUID,
	installationID installationdomain.InstallationID,
	now time.Time,
) error {
	return r.RevokeByUserIDAndInstallationID(ctx, userID, installationID.UUID(), now)
}
